services:
  postgres:
    container_name: postgres-desafio-darwoft
    image: postgres:16.2-alpine
    restart: always
    env_file:
      - .env.loc
    ports:
      - '54321:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: postgres-db-desafio-darwoft